"""Build the .nvda-addon without the GNU gettext binaries.

`sconstruct` is the canonical build and should be preferred where the gettext
tools (msgfmt, xgettext) are installed. They are not part of a normal Windows
Python install, so this script reproduces the same output using only Python's
bundled Tools/i18n/msgfmt.py plus the `markdown` package.

It performs the same steps sconstruct does:

  * render manifest.ini from manifest.ini.tpl and buildVars.addon_info
  * render addon/locale/<lang>/manifest.ini from manifest-translated.ini.tpl,
    with summary and description taken from that language's catalogue
  * compile every addon/locale/<lang>/LC_MESSAGES/nvda.po to nvda.mo
  * convert every addon/doc/<lang>/*.md to .html and copy in style.css
  * zip the addon/ directory into <name>-<version>.nvda-addon

Usage:  python build.py [--keep-intermediates]
"""

import gettext
import os
import shutil
import subprocess
import sys
import zipfile

import buildVars

HERE = os.path.dirname(os.path.abspath(__file__))
ADDON = os.path.join(HERE, "addon")
INFO = buildVars.addon_info
MSGFMT = os.path.join(os.path.dirname(sys.executable), "Tools", "i18n", "msgfmt.py")

# Files generated by this script, removed again afterwards so the working tree
# stays clean (sconstruct's own outputs are covered by .gitignore).
GENERATED = []


def fail(msg):
    print("ERROR: " + msg)
    sys.exit(1)


def render_manifest():
    with open(os.path.join(HERE, "manifest.ini.tpl"), encoding="utf-8") as f:
        tpl = f.read()
    out = os.path.join(ADDON, "manifest.ini")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(tpl.format(**INFO))
    GENERATED.append(out)
    print("  manifest.ini")


def languages():
    localeDir = os.path.join(ADDON, "locale")
    if not os.path.isdir(localeDir):
        return []
    return sorted(d for d in os.listdir(localeDir)
                  if os.path.isdir(os.path.join(localeDir, d)))


def compile_catalogues(langs):
    if not os.path.isfile(MSGFMT):
        fail("cannot find msgfmt.py at %s" % MSGFMT)
    for lang in langs:
        po = os.path.join(ADDON, "locale", lang, "LC_MESSAGES", "nvda.po")
        mo = po[:-3] + ".mo"
        if not os.path.isfile(po):
            continue
        subprocess.run([sys.executable, MSGFMT, "-o", mo, po], check=True)
        GENERATED.append(mo)
        print("  locale/%s/LC_MESSAGES/nvda.mo (%d bytes)" % (lang, os.path.getsize(mo)))


def render_translated_manifests(langs):
    tplPath = os.path.join(HERE, "manifest-translated.ini.tpl")
    if not os.path.isfile(tplPath):
        return
    with open(tplPath, encoding="utf-8") as f:
        tpl = f.read()
    for lang in langs:
        if lang == buildVars.baseLanguage:
            continue
        try:
            tr = gettext.translation("nvda", localedir=os.path.join(ADDON, "locale"),
                                     languages=[lang]).gettext
        except OSError:
            continue
        out = os.path.join(ADDON, "locale", lang, "manifest.ini")
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write(tpl.format(
                addon_summary=tr(INFO["addon_summary"]),
                addon_description=tr(INFO["addon_description"]),
            ))
        GENERATED.append(out)
        translated = tr(INFO["addon_summary"]) != INFO["addon_summary"]
        print("  locale/%s/manifest.ini%s" % (lang, "" if translated else "  (summary untranslated)"))


def build_docs():
    try:
        import markdown
    except ImportError:
        fail("the 'markdown' package is required: pip install markdown")
    docDir = os.path.join(ADDON, "doc")
    if not os.path.isdir(docDir):
        return
    css = os.path.join(HERE, "style.css")
    if os.path.isfile(css):
        target = os.path.join(docDir, "style.css")
        shutil.copyfile(css, target)
        GENERATED.append(target)
    for lang in sorted(os.listdir(docDir)):
        langDir = os.path.join(docDir, lang)
        if not os.path.isdir(langDir):
            continue
        try:
            tr = gettext.translation("nvda", localedir=os.path.join(ADDON, "locale"),
                                     languages=[lang]).gettext
        except OSError:
            tr = lambda s: s
        for name in sorted(os.listdir(langDir)):
            if not name.endswith(".md"):
                continue
            src = os.path.join(langDir, name)
            dst = src[:-3] + ".html"
            with open(src, encoding="utf-8") as f:
                mdText = f.read()
            title = "%s %s" % (tr(INFO["addon_summary"]), INFO["addon_version"])
            body = markdown.markdown(mdText, extensions=buildVars.markdownExtensions)
            html = "\n".join([
                '<!DOCTYPE html>',
                '<html lang="%s">' % lang,
                '<head>',
                '<meta charset="UTF-8">'
                '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
                '<link rel="stylesheet" type="text/css" href="../style.css" media="screen">',
                '<title>%s</title>' % title,
                '</head>',
                '<body>',
                body,
                '</body>',
                '</html>',
                '',
            ])
            with open(dst, "w", encoding="utf-8", newline="\n") as f:
                f.write(html)
            GENERATED.append(dst)
            print("  doc/%s/%s" % (lang, os.path.basename(dst)))


def package():
    name = "%s-%s.nvda-addon" % (INFO["addon_name"], INFO["addon_version"])
    out = os.path.join(HERE, name)
    excluded = set(buildVars.excludedFiles)
    files = []
    for dirpath, dirnames, filenames in os.walk(ADDON):
        # Skip build leftovers and anything local (a stray .claude or .vscode
        # directory under addon/ would otherwise be shipped to users).
        dirnames[:] = [d for d in dirnames
                       if d != "__pycache__" and not d.startswith(".")]
        for fn in filenames:
            if fn.startswith("."):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, ADDON).replace(os.sep, "/")
            if rel in excluded:
                continue
            # NOTE: do not filter *.pyc here. The legacy NVIDIAScript.exe helper
            # ships its own frozen Python runtime under data/lib as .pyc files,
            # and dropping them leaves the pre-2026.1 fallback unable to start.
            files.append((rel, full))
    files.sort(key=lambda p: (p[0] != "manifest.ini", p[0]))
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for rel, full in files:
            z.write(full, rel)
    print("\n%s  (%.2f MB, %d files)" % (name, os.path.getsize(out) / 1024 / 1024, len(files)))
    return out


def main():
    print("Building %s %s\n" % (INFO["addon_name"], INFO["addon_version"]))
    langs = languages()
    render_manifest()
    compile_catalogues(langs)
    render_translated_manifests(langs)
    build_docs()
    package()
    if "--keep-intermediates" not in sys.argv:
        for path in GENERATED:
            try:
                os.remove(path)
            except OSError:
                pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
